# kafka configurations
spring:
  kafka:
    bootstrap-servers: localhost:9092
    # Consumer configurations
    consumer:
      group-id: my-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

    # Producer configurations
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

kafka:
  topic:
    first:
      simple: first-topic
      json: first-topic-json

  ############ application.properties ############
  ### kafka configurations
  #spring.kafka.bootstrap-servers=localhost:9092
  #
  ### Consumer configurations
  #spring.kafka.consumer.group-id=my-consumer-group
  #spring.kafka.consumer.auto-offset-reset=earliest
  ## To deserialize the message key from the topic
  #spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
  ## To deserialize the message value from the topic
  ##spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
  #spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
  #spring.kafka.consumer.properties.spring.json.trusted.packages=*
  #
  ### Producer configurations
  #spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
  ##spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
  #spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
  #
  #
  ## Topics configurations
  #kafka.topic.first.simple=first-topic
  #kafka.topic.first.json=first-topic-json
